export enum ExamType {
  IELTS = "IELTS",
  TOEIC = "TOEIC",
  TOEFL = "TOEFL",
  CUSTOM = "CUSTOM",
}

export enum ExamSectionType {
  LISTENING = "LISTENING",
  READING = "READING",
  WRITING = "WRITING",
  SPEAKING = "SPEAKING",
  GENERAL = "GENERAL",
}

export enum ExamGroupType {
  LISTENING_PART = "LISTENING_PART",
  PASSAGE = "PASSAGE",
  WRITING_TASK = "WRITING_TASK",
  SPEAKING_PART = "SPEAKING_PART",
  GENERAL = "GENERAL",
}

export enum ExamQuestionType {
  MULTIPLE_CHOICE = "MULTIPLE_CHOICE",
  SHORT_ANSWER = "SHORT_ANSWER",
  MATCHING = "MATCHING",
  ESSAY = "ESSAY",
  SPEAKING_PROMPT = "SPEAKING_PROMPT",
  TRUE_FALSE_NOT_GIVEN = "TRUE_FALSE_NOT_GIVEN",
  FILL_IN_THE_BLANK = "FILL_IN_THE_BLANK",
  ORDERING = "ORDERING",
  YES_NO_NOT_GIVEN = "YES_NO_NOT_GIVEN",
  DIAGRAM_LABELING = "DIAGRAM_LABELING",
  TABLE_COMPLETION = "TABLE_COMPLETION",
  FLOWCHART_COMPLETION = "FLOWCHART_COMPLETION",
  NOTE_COMPLETION = "NOTE_COMPLETION",
}

export enum ExamAttemptStatus {
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  EXPIRED = "EXPIRED",
}

export enum ExamMode {
  FULL = "FULL",
  SECTION = "SECTION",
}
