export enum Resource {
  USER = 'USER',
  CATEGORY = 'CATEGORY',
  TOPIC = 'TOPIC',
  WORD = 'WORD',
  STUDY_SET = 'STUDY_SET',
  PROFILE = 'PROFILE',
  USER_PROGRESS = 'USER_PROGRESS',
  POST = 'POST',
  COMMENT = 'COMMENT',
  LIKE = 'LIKE',
  WITHDRAWAL = 'WITHDRAWAL',
}
